
server:
  port: 8282





#server:
#  port: 8282
#  ssl:
#    key-store: classpath:myapp.p12
#    key-store-password: 12345
#    key-store-type: PKCS12
#    key-alias: myapp
#    
#    
    

#================================
#        PKCS12
#================================
#server:
#  port: 8282
#  ssl:
#    enabled: true
#    key-alias: myapp
#    key-store: classpath:myapp-keystore.p12
#    key-store-password: secret
#    key-store-type: PKCS12


#================================
#        JKS
#================================
#server:
#  port: 8282
#  ssl:
#    enabled: true
#    key-alias: spapp1
#    key-store: classpath:myspringboot.jks
#    key-store-password: appsecpass
#    key-store-type: JKS
#    key-store-provider: SUN
#    








management:
  endpoints:
    web:
      exposure:
        include: "*"













