server:
  port: 8282
  ssl:
    enabled: true
    key-alias: myapp
    key-store: classpath:myapp-keystore.p12
    key-store-password: secret
    key-store-type: PKCS12





















management:
  endpoints:
    web:
      exposure:
        include: "*"








